# Generated by Django 5.2.9 on 2025-12-09 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
