# Generated by Django 5.2.9 on 2025-12-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_sizevariant_product_alter_sizevariant_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='shop.product'),
        ),
    ]
